### ISSUE TITLE
The list of servers should be a configuration file

### ISSUE THREAD

**Issue by arodier** [phoemur/ipgetter#30]
The list of servers should be a configuration file, it is pure data.
Perhaps a YAML file, that would list the type of return as well, for instance:

```yaml
servers:
  - url: http://www.ip-adress.com
    format: html
  - url: http://myexternalip.com/raw
    format: text
  - url: http://ip.jsontest.com/
    format: json
```
Therefore, adding new servers would not impact the code updates.
